apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-role-devops
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["configMaps", "secrets", "”endpoints", "nodes", "pods", "”services", "namespaces", "events", "serviceAccounts"]
  verbs: ["get", "watch", "list", "patch", "update"]