apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: claim-log-1
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/log/nginx"
          name: pv-storage