apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: c3FsMDE=           #sql01
  MYSQL_USER: dXNlcjE=                 #user1 
  MYSQL_PASSWORD: cGFzc3dvcmQ=                #password 
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM=           #password123
